/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SegurosSlugRouteImport } from './routes/seguros/$slug'
import { Route as CotacaoAutoRouteImport } from './routes/cotacao/auto'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurosSlugRoute = SegurosSlugRouteImport.update({
  id: '/seguros/$slug',
  path: '/seguros/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacaoAutoRoute = CotacaoAutoRouteImport.update({
  id: '/cotacao/auto',
  path: '/cotacao/auto',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cotacao/auto': typeof CotacaoAutoRoute
  '/seguros/$slug': typeof SegurosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cotacao/auto': typeof CotacaoAutoRoute
  '/seguros/$slug': typeof SegurosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cotacao/auto': typeof CotacaoAutoRoute
  '/seguros/$slug': typeof SegurosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cotacao/auto' | '/seguros/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cotacao/auto' | '/seguros/$slug'
  id: '__root__' | '/' | '/cotacao/auto' | '/seguros/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CotacaoAutoRoute: typeof CotacaoAutoRoute
  SegurosSlugRoute: typeof SegurosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguros/$slug': {
      id: '/seguros/$slug'
      path: '/seguros/$slug'
      fullPath: '/seguros/$slug'
      preLoaderRoute: typeof SegurosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacao/auto': {
      id: '/cotacao/auto'
      path: '/cotacao/auto'
      fullPath: '/cotacao/auto'
      preLoaderRoute: typeof CotacaoAutoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CotacaoAutoRoute: CotacaoAutoRoute,
  SegurosSlugRoute: SegurosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
