/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SegurosSlugRouteImport } from './routes/seguros/$slug'
import { Route as CotacaoAutoRouteImport } from './routes/cotacao/auto'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurosSlugRoute = SegurosSlugRouteImport.update({
  id: '/seguros/$slug',
  path: '/seguros/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacaoAutoRoute = CotacaoAutoRouteImport.update({
  id: '/cotacao/auto',
  path: '/cotacao/auto',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/cotacao/auto': typeof CotacaoAutoRoute
  '/seguros/$slug': typeof SegurosSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/cotacao/auto': typeof CotacaoAutoRoute
  '/seguros/$slug': typeof SegurosSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/cotacao/auto': typeof CotacaoAutoRoute
  '/seguros/$slug': typeof SegurosSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/login'
    | '/cotacao/auto'
    | '/seguros/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/login' | '/cotacao/auto' | '/seguros/$slug' | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin/login'
    | '/cotacao/auto'
    | '/seguros/$slug'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  CotacaoAutoRoute: typeof CotacaoAutoRoute
  SegurosSlugRoute: typeof SegurosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguros/$slug': {
      id: '/seguros/$slug'
      path: '/seguros/$slug'
      fullPath: '/seguros/$slug'
      preLoaderRoute: typeof SegurosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacao/auto': {
      id: '/cotacao/auto'
      path: '/cotacao/auto'
      fullPath: '/cotacao/auto'
      preLoaderRoute: typeof CotacaoAutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  CotacaoAutoRoute: CotacaoAutoRoute,
  SegurosSlugRoute: SegurosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
